### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by akozd** [aws-samples/generative-ai-sagemaker-cdk-demo#1]
1. The role [assumed](https://github.com/aws-samples/generative-ai-sagemaker-cdk-demo/blob/main/stack/generative_ai_demo_web_stack.py#L21) by the Lambda is overly permissive. You really just need `sagemaker:InvokeEndpoint` (and specify the two endpoint resource names as well via the `resource` part of the IAM policy).
2. Your APIGWs are exposed to the world. Consider creating them in the private VPC where your Lambda sits, or adding a resource policy so that only the Lambda's execution role is able to invoke them. Bonus points if you do both.
3. Your SageMaker endpoints' role is also [overly permissioned](https://github.com/aws-samples/generative-ai-sagemaker-cdk-demo/blob/main/stack/generative_ai_txt2nlu_sagemaker_stack.py#L15-L16)
4. Consider running a formatter like [black](https://black.readthedocs.io/en/stable/) to make the code follow pep8 standards

**Comment by Hantzley** [comment]
@akozd - Thanks for the suggestions and tips.
