### ISSUE TITLE
Issue with creating the CFN stacks containing sagemaker inference endpoints

### ISSUE THREAD

**Issue by arkaprava08** [aws-samples/generative-ai-sagemaker-cdk-demo#2]
There is an issue with the cdk stack "GenerativeAiTxt2imgSagemakerStack" where the role gets created before inline policy is attached which leads to error:

The role 'arn:aws:iam::-----:role/GenerativeAiTxt2imgSagema-GenAISageMakerPolicyBF71-YHN96BM6FSVV' does not have BatchGetImage permission for the image: '[763104351884.dkr.ecr.us-wes...](http://disq.us/url?url=http%3A%2F%2F763104351884.dkr.ecr.us-west-2.amazonaws.com%2Fhuggingface-pytorch-inference%3A1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04%27%3ApkxgqX1MuTu5wmlCf014ZK95J18&cuid=4792734).

Had to change this in both the places:
[generative_ai_txt2nlu_sagem...](http://disq.us/url?url=http%3A%2F%2Fgenerative_ai_txt2nlu_sagemaker_stack.py%3AdOxbBb3xTvhTxRoiS8Ed_gjtjJk&cuid=4792734)
[generative_ai_txt2img_sagem...](http://disq.us/url?url=http%3A%2F%2Fgenerative_ai_txt2img_sagemaker_stack.py%3ASt9jL2Y1zpT8pbzu_Lfjcj3Wrzc&cuid=4792734)
```

.......
sts = iam.Policy(self, "sm-deploy-policy-sts",
statements=[iam.PolicyStatement(
effect=iam.Effect.ALLOW,
actions=[
"sts:AssumeRole"
],
resources=["*"]
)]
)

logs = iam.Policy(self, "sm-deploy-policy-logs",
statements=[iam.PolicyStatement(
effect=iam.Effect.ALLOW,
actions=[
"cloudwatch:PutMetricData",
"logs:CreateLogStream",
"logs:PutLogEvents",
"logs:CreateLogGroup",
"logs:DescribeLogStreams",
"ecr:GetAuthorizationToken"
],
resources=["*"]
)]
)

ecr = iam.Policy(self, "sm-deploy-policy-ecr",
statements=[iam.PolicyStatement(
effect=iam.Effect.ALLOW,
actions=[
"ecr:*",
],
resources=["*"]
)]
)

role.attach_inline_policy(sts)
role.attach_inline_policy(logs)
role.attach_inline_policy(ecr)

endpoint = SageMakerEndpointConstruct(self, "TXT2IMG",
.....
)
endpoint.node.add_dependency(sts)
endpoint.node.add_dependency(ecr)
endpoint.node.add_dependency(logs)
```

**Comment by Hantzley** [comment]
@arkaprava08 - Great suggestion. I've added it to the code. See:

https://github.com/aws-samples/generative-ai-sagemaker-cdk-demo/blob/main/stack/generative_ai_txt2nlu_sagemaker_stack.py 

https://github.com/aws-samples/generative-ai-sagemaker-cdk-demo/blob/main/stack/generative_ai_txt2img_sagemaker_stack.py
