### ISSUE TITLE
Webapp deployed using my M1 Mac fails to come inService

### ISSUE THREAD

**Issue by arkaprava08** [aws-samples/generative-ai-sagemaker-cdk-demo#3]
Another issue found where the webapp does not deploy successfully when i run cdk commands from my mac M1. I think the docker image generated on mac m1 has some issues. This was resolved when i ran in my linux x86 machine

**Comment by Hantzley** [comment]
I tested the code on AWS Cloud9 and Apple Mac M2. It works fine.

Can you try replacing the first line in the [Dockerfile](https://github.com/aws-samples/generative-ai-sagemaker-cdk-demo/blob/841f0d8d30ed32d592f7082cc6b1e8f2ed6a715c/web-app/Dockerfile#L1) with the following and run it from your Apple Mac M1?

`FROM --platform=linux/x86_64 python:3.9`
