### ISSUE TITLE
cognito login and hosting URL on cloudfront

### ISSUE THREAD

**Issue by monuminu** [aws-samples/generative-ai-sagemaker-cdk-demo#6]
Hi Team,

The hosted URL is on http . Is there any plan on hosting the same on cloudfront and enable cognito like we do in QnA bot. Any reference python cdk code

**Comment by Hantzley** [comment]
Hello Manoranjan,

We provided this as a sample app with the base infrastructure, offering the flexibility for users to extend it with features like Cognito, API Gateway usage plans, CloudFront, etc... 

In this project, we have no plans to extend it. But we can certainly consider another project with these features.
